var composition = {
       "rest": "0:0:0",
       "events":[
          {
             "note":"C3",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":0,
             "time":"0:0:0",
             "velocity":0.7,
             "active":false
          },
          {
             "note":"E4",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":0,
             "time":"0:0:0",
             "velocity":0.9,
             "active":false
          },
          {
             "note":"G3",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":0,
             "time":"0:0:0",
             "velocity":0.5,
             "active":false
          },
          {
             "note":"G3",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":2,
             "time":"0:2:0",
             "velocity":0.7,
             "active":false
          },
          {
             "note":"B4",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":2,
             "time":"0:2:0",
             "velocity":0.9,
             "active":false
          },
          {
             "note":"D3",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":2,
             "time":"0:2:0",
             "velocity":0.5,
             "active":false
          },
          {
             "note":"F3",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":4,
             "time":"1:0:0",
             "velocity":0.7,
             "active":false
          },
          {
             "note":"A4",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":4,
             "time":"1:0:0",
             "velocity":0.9,
             "active":false
          },
          {
             "note":"C4",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":4,
             "time":"1:0:0",
             "velocity":0.5,
             "active":false
          },
          {
             "note":"A3",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":6,
             "time":"1:2:0",
             "velocity":0.7,
             "active":false
          },
          {
             "note":"C4",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":6,
             "time":"1:2:0",
             "velocity":0.9,
             "active":false
          },
          {
             "note":"E3",
             "rawDuration":2,
             "duration":"0:2:0",
             "rawTime":6,
             "time":"1:2:0",
             "velocity":0.5,
             "active":false
          }
       ]
 }

 export { composition }