var config = {
    "patchName":"",
    "partialsConfig":[
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0
    ],
    "envelopeConfig":{
       "attack":1.5,
       "attackCurve":"linear",
       "decay":0.4,
       "sustain":0.5,
       "release":0.5,
       "releaseCurve":"linear"
    },
    "eq3Config":{
       "low":0,
       "lowFrequency":440,
       "mid":0,
       "high":0,
       "highFrequency":2500
    },
    "chorusConfig":{
       "delayTime":0.001,
       "depth":0,
       "feedback":0,
       "frequency":0,
       "spread":0,
       "wet":0
    },
    "tremoloConfig":{
       "frequency":0,
       "depth":0,
       "spread":0,
       "wet":0
    },
    "vibratoConfig":{
       "maxDelay":0.001,
       "frequency":0,
       "depth":0,
       "wet":0
    },
    "pingPongDelayConfig":{
       "delayTime":0.001,
       "feedback":0,
       "maxDelay":5,
       "wet":0
    },
    "reverbConfig":{
       "decay":0.001,
       "wet":0
    },
    "feedbackDelayConfig":{
       "maxDelay":15,
       "delayTime":0.001,
       "feedback":0,
       "wet":0
    }
 }

 export { config }